name: Generate API Client

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    env:
      ReleaseVersion: '2.0.0'
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Docker Command
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/:/packages openapitools/openapi-generator-cli generate \
          -i 'https://stoplight.io/api/v1/projects/spacetraders/spacetraders/nodes/reference/SpaceTraders.json?fromExportButton=true&snapshotType=http_service&deref=optimizedBundle' \
          -g go \
          -o packages \
          --git-user-id AndrewShear \
          --git-repo-id spacetraders \
          --additional-properties packageName="spacetraders" \
          --additional-properties packageVersion="$ReleaseVersion" \
          --additional-properties enumClassPrefix=true \
          --additional-properties structPrefix=true \
          --additional-properties withSeparateModelsAndApi=true \
          --additional-properties modelPackage="models" \
          --additional-properties apiPackage="api"

    - name: Go Mod Tidy
      run: |
        go mod tidy

    - name: Check for Changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "No changes to commit."
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected, proceeding with commit."
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and Push Generated Files
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.email "noreply@spiri.dev"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Generate API client"
        git tag v$ReleaseVersion
        git push origin HEAD --tags
        if [ $? -ne 0 ]; then 
          echo "error pushing to origin"
        fi

    - name: Cut Release
      run: |
        release_output=$(gh release view v$ReleaseVersion 2>&1)
        if [[ "$release_output" == *"release not found"* ]]; then
          echo "Release not found. Creating a new release..."
          gh release create v$ReleaseVersion --generate-notes
          if [ $? -ne 0 ]; then
            echo "could not cut release for v$ReleaseVersion"
            exit 1
          fi
        fi
