name: Generate API Client

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      release_version:
        description: 'Version for the release'
        default: '2.0.0'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Docker Command
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/:/packages openapitools/openapi-generator-cli generate \
          -i 'https://stoplight.io/api/v1/projects/spacetraders/spacetraders/nodes/reference/SpaceTraders.json?fromExportButton=true&snapshotType=http_service&deref=optimizedBundle' \
          -g go \
          -o packages \
          --git-user-id AndrewShear \
          --git-repo-id spacetraders \
          --additional-properties packageName="spacetraders" \
          --additional-properties packageVersion="${{ inputs.release_version }}" \
          --additional-properties enumClassPrefix=true \
          --additional-properties structPrefix=true \
          --additional-properties withSeparateModelsAndApi=true \
          --additional-properties modelPackage="models" \
          --additional-properties apiPackage="api"

    - name: Commit and Push Generated Files
      env:
        GH_TOKEN: ${{ github.GITHUB_TOKEN }}
      run: |
        git config --global user.email "noreply@spiri.dev"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Generate API client"
        git tag v${{ inputs.release_version }}
        git push
        gh release create v${{ inputs.release_version }}
